### ISSUE TITLE
[PE-D][Tester B] Lab sessions not considered as a lesson type

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-3/tp#148]
It is stated in the user guide: The LESSON_TYPE can be either lecture, tutorial.

However, if the product were to be a *simplified Module Organizer and Manager application*, then the identification of all lesson types is critical. Especially for common lesson types like "LAB", it makes the product unusable if the student cannot select their LAB session, or any lesson types for whatever module they are taking. Although the severity indicated is Low, it can easily be Medium or High, if the student is taking many modules with unrecognised lesson types.

![bug2.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/b6378b1d-8ff0-46f2-b94f-a0ba947d4fd8.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cheehengk/ped#2

**Comment by amitrahman1026** [comment]
fixed in #144

**Comment by amitrahman1026** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/70333123/198879401-c0a8f010-7957-41f7-9101-e084e09aab59.png">
I am guessing you might have not added the module cs1010 before selecting the lab slot
