### ISSUE TITLE
[PE-D][Tester D] View fancy is not understandable

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-3/tp#151]
![image.png](https://raw.githubusercontent.com/ishitamandal06/ped/main/files/6aa32c44-4152-44fb-91a1-96b35328305b.png)

I can understand the output when I put view or view /simple. When I put view/fancy, it is very hard to understand what the output is showing. Maybe this can be made simpler?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ishitamandal06/ped#1

**Comment by owenl131** [comment]
Added to user guide.
