### ISSUE TITLE
[PE-D][Tester A] Timetable view 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-3/tp#155]
![image.png](https://raw.githubusercontent.com/markusteim/ped/main/files/327d434d-48a1-41ad-9128-c45c174b338b.png)
The text seems to be going out of the barriers for some cases

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: markusteim/ped#1

**Comment by amitrahman1026** [comment]
It is by design
