### ISSUE TITLE
[PE-D][Tester A] Import doesn't properly get all the modules

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-3/tp#162]
![image.png](https://raw.githubusercontent.com/markusteim/ped/main/files/3ffc7bde-b510-4f86-8d28-ffee1f48b1f0.png)

![image.png](https://raw.githubusercontent.com/markusteim/ped/main/files/bd229b0a-36cd-4e93-9d17-e600c78feb6f.png)

Steps 1) Added LC2008A to the module list
2) Exported the timetable
3) Added another module in NUSMODS
4) Imported and would not recognize the new added module

It gave confirmation that it could import it 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: markusteim/ped#2

**Comment by kohnh** [comment]
Could you instead provide the actual commands input in YAMOM instead of telling the steps? If the error is repeatable then it would probably be a bug and not a user error. Will test it out to see if it occurs on our end.

**Comment by kohnh** [comment]
This is due to this module not being able to be found when searching for this mod in YAMOM.
![image](https://user-images.githubusercontent.com/64647635/198813493-d93ac27b-0e65-4b43-aef4-578dea5ad6be.png)
Will fix.

**Comment by owenl131** [comment]
Fixed.
