### ISSUE TITLE
[PE-D][Tester B] Module selection allows for invalid lesson code

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-3/tp#163]
In the below image, when given a clearly invalid module code (as an integer), the program accepts it and tells the user that the selection is successful. In the `view` function, this invalid lesson is completely not reflected and in the `list` function, the program reflects the invalid lesson code. This bug exists for both tutorial (the supposed accepted lesson type) and sectional teaching.

![bug5.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/acbc7aed-6a97-4707-9753-bb31760cf889.png)

![bug 5a.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/2b5d0266-d7de-47da-bf5e-2bcde4a455c4.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: cheehengk/ped#5

**Comment by amitrahman1026** [comment]
Fixed in #144
