### ISSUE TITLE
[PE-D][Tester B] Module selection command convention inconsistent with User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-3/tp#166]
As shown in the image, using `lec` instead of `lecture` as the lesson type is acceptable but this option is missing from the User Guide.

![bug7.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/c8660ef3-b818-4116-8df3-0572a75af63d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cheehengk/ped#7

**Comment by amitrahman1026** [comment]
This is a documentation bug
