### ISSUE TITLE
[PE-D][Tester B] Command-D causes some infinite loop

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-3/tp#169]
When entering Command-D on the terminal (Mac), the program enters an infinite loop. Considered Low severity as the average user will not enter this command.

![bug8.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/275a3010-fe31-4c0d-86c8-308e55460b92.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cheehengk/ped#8

**Comment by owenl131** [comment]
Fixed.
