### ISSUE TITLE
[PE-D][Tester B] Command casing format inconsistent with User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-3/tp#182]
In the user guide, it is stated that ***Words in UPPERCASE information to be supplied by the user***. However, lower case commands are also allowed. There is some inconsistency, possibly from the user guide not being updated in time to reflect the removal of this restriction.

![Screenshot 2022-10-28 at 5.39.28 PM.png](https://raw.githubusercontent.com/cheehengk/ped/main/files/6e0ddac1-ad7d-4a6a-9296-cffca2198069.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: cheehengk/ped#14

**Comment by amitrahman1026** [comment]
I believe you are misunderstanding the sentence "Words in UPPERCASE information to be supplied by the user. " - The UPPERCASE information simply refers to the field user must input.

If you look at the feature descriptions below, you will find that we mention that the user supplied input is not case-sensitive.

![image](https://user-images.githubusercontent.com/70333123/198818774-3fd4d4f5-baaa-4faa-b6f8-8f8428e11310.png)
