### ISSUE TITLE
Fix empty data file bug

### ISSUE THREAD

**Issue by CheahHaoYi** [AY2223S1-CS2113-F11-3/tp#68]
Nullpointer exception in SelectedModule (main, int, Storage.openPreviousState, Storage.loadPreviousState) when the programme is run after an empty previous run (the user does not add anything in the previous run)

The duke.txt file contains `https://nusmods.com/timetable/sem-1/share?` only

**Comment by owenl131** [comment]
iirc also had an error if duke.txt exists but is empty.
